INSERT INTO frequently_asked_questions (question, title) VALUES ('Have you passed a background check?', 'background check');
INSERT INTO frequently_asked_questions (question, title) VALUES ('How many employees does your company have?', 'number of employees');
INSERT INTO frequently_asked_questions (question, title) VALUES ('How long have your company been operating for?', 'company\'s age');
INSERT INTO frequently_asked_questions (question, title) VALUES ('Who is the founder of your company?', 'company founder');
INSERT INTO frequently_asked_questions (question, title) VALUES ('Are there any promotional offers?', 'promotional offers');
INSERT INTO frequently_asked_questions (question, title) VALUES ('What sets you apart from other service providers?', 'selling point');
INSERT INTO frequently_asked_questions (question, title) VALUES ('Have you passed a background check?', 'background check');
INSERT INTO frequently_asked_questions (question, title) VALUES ('What kind of insurance do you have?', 'insurance');
INSERT INTO frequently_asked_questions (question, title) VALUES ('Are your end client happy?', 'client');
INSERT INTO frequently_asked_questions (question, title) VALUES ('What is your specialization?', 'specialization');
INSERT INTO frequently_asked_questions (question, title) VALUES ('Are there free swags?', 'swags');
INSERT INTO frequently_asked_questions (question, title) VALUES ('Where are you located?', 'location');
INSERT INTO frequently_asked_questions (question, title) VALUES ('Are there any extra service fees?', 'extra fees');
INSERT INTO frequently_asked_questions (question, title) VALUES ('What are you most experienced in doing?', 'experience');
INSERT INTO frequently_asked_questions (question, title) VALUES ('Who are your target clients?', 'target clients');
INSERT INTO frequently_asked_questions (question, title) VALUES ('Do you have any branches?', 'branches');
INSERT INTO frequently_asked_questions (question, title) VALUES ('Are you available during the weekends?', 'weekends');
INSERT INTO frequently_asked_questions (question, title) VALUES ('Are your technicians properly trained?', 'experts');
INSERT INTO frequently_asked_questions (question, title) VALUES ('What is your refund policy?', 'refund');
INSERT INTO frequently_asked_questions (question, title) VALUES ('What is special about your company?', 'about company');
INSERT INTO frequently_asked_questions (question, title) VALUES ('Are there any extra service charge?', 'extra charge');
INSERT INTO frequently_asked_questions (question, title) VALUES ('When can I expect to be scheduled?', 'scheduling');
INSERT INTO frequently_asked_questions (question, title) VALUES ('Can I make changes to my appointment?', 'appointment');
INSERT INTO frequently_asked_questions (question, title) VALUES ('Do I have to show my identification at the appointment?', 'id required?');
INSERT INTO frequently_asked_questions (question, title) VALUES ('How many customers have you worked with so far?', 'no. of customers');
INSERT INTO frequently_asked_questions (question, title) VALUES ('What is your safety policy?', 'safety');
INSERT INTO frequently_asked_questions (question, title) VALUES ('What should I do if I am not satisfied with your service?', 'complaints');
INSERT INTO frequently_asked_questions (question, title) VALUES ('Describe yourself in three words.', 'three adjectives');