INSERT INTO services (id, title, score) VALUES (123, 'House Cleaners', 30);
INSERT INTO services (id, title, score) VALUES (234, 'Interior Painters', 45);
INSERT INTO services (id, title, score) VALUES (345, 'Handymen', 0);
INSERT INTO services (id, title, score) VALUES (456, 'Photographers', 250);
INSERT INTO services (id, title, score) VALUES (567, 'Makeup Artists', 160);
INSERT INTO services (id, title, score) VALUES (678, 'Dog Groomers', 330);
INSERT INTO services (id, title, score) VALUES (789, 'Dog Trainers', 200);
INSERT INTO services (id, title, score) VALUES (890, 'Pet Sitters', 120);
INSERT INTO services (id, title, score) VALUES (321, 'Math Tutoring', 500);
INSERT INTO services (id, title, score) VALUES (432, 'Piano Lessons', 21);
INSERT INTO services (id, title, score) VALUES (543, 'Personal Training', 10);
INSERT INTO services (id, title, score) VALUES (1, 'Dog Walking', 75);
INSERT INTO services (id, title, score) VALUES (2, 'Dog Care', 95);
INSERT INTO services (id, title, score) VALUES (3, 'Dog Training', 100);
INSERT INTO services (id, title, score) VALUES (4, 'Dog\'s Birthday Party', 87);
INSERT INTO services (id, title, score) VALUES (5, 'Pet Care', 19);