INSERT INTO services (id, title, score) VALUES (123, 'House Cleaners', 30);
INSERT INTO services (id, title, score) VALUES (234, 'Interior Painters', 45);
INSERT INTO services (id, title, score) VALUES (345, 'Handymen', 0);
INSERT INTO services (id, title, score) VALUES (456, 'Photographers', 250);
INSERT INTO services (id, title, score) VALUES (567, 'Makeup Artists', 160);
INSERT INTO services (id, title, score) VALUES (678, 'Dog Groomers', 330);
INSERT INTO services (id, title, score) VALUES (789, 'Dog Trainers', 200);
INSERT INTO services (id, title, score) VALUES (890, 'Pet Sitters', 120);
INSERT INTO services (id, title, score) VALUES (321, 'Math Tutoring', 500);
INSERT INTO services (id, title, score) VALUES (432, 'Piano Lessons', 21);
INSERT INTO services (id, title, score) VALUES (543, 'Personal Training', 10);
INSERT INTO services (id, title, score) VALUES (1, 'Dog Walking', 75);
INSERT INTO services (id, title, score) VALUES (2, 'Dog Care', 95);
INSERT INTO services (id, title, score) VALUES (3, 'Dog Training', 100);
INSERT INTO services (id, title, score) VALUES (4, 'Dog\'s Birthday Party', 87);
INSERT INTO services (id, title, score) VALUES (5, 'Pet Care', 19);
INSERT INTO services (id, title, score) VALUES (6, 'Business Analysts', 1);
INSERT INTO services (id, title, score) VALUES (7, 'Business Consultants', 5);
INSERT INTO services (id, title, score) VALUES (8, 'Digital Marketers', 2);
INSERT INTO services (id, title, score) VALUES (9, 'Event Organizers', 0);
INSERT INTO services (id, title, score) VALUES (10, 'Health Consultants', 10);
INSERT INTO services (id, title, score) VALUES (11, 'Body Trainers', 25);
INSERT INTO services (id, title, score) VALUES (12, 'Food Services', 1);
INSERT INTO services (id, title, score) VALUES (13, 'Food Advisor', 5);
INSERT INTO services (id, title, score) VALUES (14, 'Web Designers', 3);
INSERT INTO services (id, title, score) VALUES (15, 'Software Engineers', 20);
INSERT INTO services (id, title, score) VALUES (16, 'Networks Engineers', 2);
INSERT INTO services (id, title, score) VALUES (17, 'Lawyers', 0);