INSERT INTO service_categories (title, score) VALUES ('Pets', 300);
INSERT INTO service_categories (title, score) VALUES ('Weddings', 260);
INSERT INTO service_categories (title, score) VALUES ('Business', 240);
INSERT INTO service_categories (title, score) VALUES ('Events', 0);
INSERT INTO service_categories (title, score) VALUES ('Wellness', 0);
INSERT INTO service_categories (title, score) VALUES ('Lessons', 0); 
INSERT INTO service_categories (title, score) VALUES ('Crafts', 0); 
INSERT INTO service_categories (title, score) VALUES ('Design and Web', 0); 
INSERT INTO service_categories (title, score) VALUES ('Legal', 0); 
INSERT INTO service_categories (title, score) VALUES ('Personal', 0);
INSERT INTO service_categories (title, score) VALUES ('Photography', 1);